### ISSUE TITLE
why i installed it, it isn't in my Xcode->structure

### ISSUE THREAD

**Issue by oikios** [jkmathew/JKBlockCommenter#6]

**Comment by NikKovV** [comment]
No Xcode 7.3 support

**Comment by Johnykutty** [comment]
@oikios its not in structure, select the code you what to comment, then Press `⌘`, `⌥` and `/` keys together or From `Edit` menu select `Comment Selection With /* ... */`

@NikKovV added Xcode 7.3 support, update/ uninstall then install again.
